# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI


on:
  push:
    paths-ignore:
      - 'docs/**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
        mongodb-version: [ ^4.0.0, ^5.0.0, ^6.0.0 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup MongoDB
        run: pnpm install --filter=@fizzbuds/ddd-toolkit mongodb@${{ matrix.mongodb-version }}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  should_publish_on_npm:
    name: check if NPM_TOKEN is set in github secrets
    runs-on: ubuntu-latest
    outputs:
      SHOULD_PUBLISH_ON_NPM: ${{ steps.should_publish_on_npm_job.outputs.SHOULD_PUBLISH_ON_NPM }}
    steps:
      - id: should_publish_on_npm_job
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            echo "SHOULD_PUBLISH_ON_NPM: ${{ env.NPM_TOKEN != '' }}"
            echo "SHOULD_PUBLISH_ON_NPM=${{ env.NPM_TOKEN != '' }}" >> $GITHUB_OUTPUT

  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build, should_publish_on_npm]

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@fizzbuds'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create and publish versions on NPM
        uses: changesets/action@v1
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        with:
          publish: pnpm ci:publish --no-git-checks

      - run: echo "tag=main-$(date -u +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        id: tag
      - name: Zip toolkit directory
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        run: |
          cd packages/ddd-toolkit
          pnpm pack --out ../../ddd-toolkit.tgz
      - name: Create and publish versions on github
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ddd-toolkit.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

